services:
    traefik:
        image: traefik:v3
        command:
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
            - --certificatesresolvers.le.acme.email=${ACME_EMAIL}
            - --certificatesresolvers.le.acme.storage=/acme/acme.json
            - --entrypoints.web.http.redirections.entrypoint.to=websecure
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - acme:/acme
        restart: unless-stopped

    app:
        build:
            context: .
            args:
                GIT_REVISION: ${GIT_REVISION}
        labels:
            - traefik.enable=true
            - traefik.http.routers.app.rule=Host(`app.betaflight-remote.com`)
            - traefik.http.routers.app.tls.certresolver=le
            - traefik.http.services.app.loadbalancer.server.port=80
            - traefik.http.routers.root.rule=Host(`betaflight-remote.com`)
            - traefik.http.routers.root.tls.certresolver=le
            - traefik.http.routers.root.middlewares=root-redirect
            - traefik.http.middlewares.root-redirect.redirectregex.regex=^https?://betaflight-remote.com(.*)
            - traefik.http.middlewares.root-redirect.redirectregex.replacement=https://app.betaflight-remote.com$${1}
            - traefik.http.middlewares.root-redirect.redirectregex.permanent=true
        restart: unless-stopped

    relay:
        build: ./broker
        labels:
            - traefik.enable=true
            - traefik.http.routers.relay.rule=Host(`relay.betaflight-remote.com`)
            - traefik.http.routers.relay.tls.certresolver=le
            - traefik.http.services.relay.loadbalancer.server.port=8765
        restart: unless-stopped

volumes:
    acme:
